### ISSUE TITLE
won't work with log4js

### ISSUE THREAD

**Issue by papercranedev-steve** [ericclemmons/start-server-webpack-plugin#25]
As the server starts,all the logs generated by log4js are not displayed on the terminal while displayed when using  'node server.js' to start the server.
here's the logger wrapper js. 
```javascript
import { log4js as logConfig } from 'config';
import * as log4js from 'log4js'

log4js.configure(logConfig);

const logger = log4js.getLogger('console');
console.log = logger.info.bind(logger);
console.debug = logger.debug.bind(logger);
console.error = logger.error.bind(logger);

export default category => log4js.getLogger(category);

```

**Comment by papercranedev-steve** [comment]
I think it's better to ask such questions at stackoverflow,so i'll close the issue.
Sorry for the interference..

**Comment by wmertens** [comment]
Ah yes indeed, but can you also link to the SO question so future searchers
can find the answer?
