### ISSUE TITLE
args problem?

### ISSUE THREAD

**Issue by Adherentman** [ericclemmons/start-server-webpack-plugin#29]
I want `node dist/index.bundle.js | node_modules/.bin/bunyan -o short`
but I try
```javascript
{ 
  nodeArgs || args: ['node_modules/.bin/bunyan -o short'] 
  
}
```
And
```javascript
{ 
  nodeArgs ||  args: ['| node_modules/.bin/bunyan -o short'] 
}
```
But it didn't work

**Comment by wmertens** [comment]
You can't start a pipe command with this plugin. You should run `webpack
..... | npx bunyan -o short`

Wout.

**Comment by Adherentman** [comment]
@wmertens ok,Thenks , I forget npm scripts.. sorry!
